name: model_viewer_plus
version: 1.5.1
description: A Flutter widget for rendering interactive 3D models in the glTF and GLB formats.
homepage: https://github.com/omchiii/model_viewer_plus.dart
repository: https://github.com/omchiii/model_viewer_plus.dart
issue_tracker: https://github.com/omchiii/model_viewer_plus.dart/issues
platforms:
  android:
  ios:
  web:
dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^4.0.1
  path: ^1.8.2
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.8.2
  webview_flutter_wkwebview: ^3.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"
flutter:
  assets:
    - assets/
