name: model_viewer_plus
description: "A Flutter widget for rendering interactive 3D models in the glTF and GLB formats"
version: 1.8.1
repository: https://github.com/omchiii/model_viewer_plus.dart
topics:
  - model-viewer
  - model
platforms:
  android:
  ios:
  web:
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  android_intent_plus: ^5.0.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  url_launcher: ^6.2.1
  web: '>=0.5.1 <2.0.0'
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  carapacik_lints: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
